const toursDetails = [
  {
    id: 1,
    title: "Everest Base Camp",
    image: "/images/everest.jpeg",
    price: 999,
    location: "Nepal",
    featured: true,
    reviews: [
      { id: 'r1', userId: 'u1', rating: 5, comment: 'Amazing trek!' },
      { id: 'r2', userId: 'u2', rating: 4, comment: 'Great experience.' },
      { id: 'r3', userId: 'u3', rating: 5, comment: 'Breathtaking views.' },
    ],
  },
  {
    id: 2,
    title: "Annapurna Circuit Trek",
    image: "/images/annapurna.jpeg",
    price: 850,
    location: "Nepal",
    featured: false,
    reviews: [
      { id: 'r4', userId: 'u4', rating: 4 },
      { id: 'r5', userId: 'u5', rating: 3 },
    ],
  },
  {
    id: 3,
    title: "Chitwan Jungle Safari",
    image: "/images/chitwan.jpeg",
    price: 300,
    location: "Nepal",
    avgRating: 4.2,
    reviews: 65,
    featured: true,
  },
  {
    id: 4,
    title: "Pokhara City Tour",
    image: "/images/pokhara.jpeg",
    price: 150,
    location: "Nepal",
    avgRating: 4.0,
    reviews: 42,
    featured: true,
  },
  {
    id: 5,
    title: "Lumbini Pilgrimage Tour",
    image: "/images/lumbini.jpeg",
    price: 180,
    location: "Nepal",
    avgRating: 4.5,
    reviews: 78,
    featured: true,
  },
  {
    id: 6,
    title: "Rara Lake Adventure",
    image: "/images/rara.jpeg",
    price: 950,
    location: "Nepal",
    avgRating: 4.7,
    reviews: 110,
    featured: true,
  },
  {
    id: 7,
    title: "Muktinath Temple Darshan",
    image: "/images/muktinath.jpg",
    price: 450,
    location: "Nepal",
    avgRating: 4.3,
    reviews: 55,
    featured: true,
  },
  {
    id: 8,
    title: "Ilam Tea Garden Experience",
    image: "/images/ilam.jpeg",
    price: 220,
    location: "Nepal",
    avgRating: 4.1,
    reviews: 38,
    featured: true,
  },
  
  {
    id: 9,
    title: "Bandipur Cultural Retreat",
    image: "/images/bandipur.webp",
    price: 275,
    location: "Nepal",
    avgRating: 4.4,
    reviews: 47,
    featured: true,
  },
];

export default toursDetails;