import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./users/header/page";
import Footer from "./users/footer/page";






const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Land Cruiser_Krisha_sadhan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Header/>      
        {children}        
        <Footer />
       
      </body>
    </html>
  );
}
